package pageobjects;

import java.util.List;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

import com.provar.core.testapi.annotations.*;

@SalesforcePage( title="Incap 311__ Base 311_ Dupe STV Config"                                
               , summary=""
               , page="Base311_DupeSTVConfig"
               , namespacePrefix="Incap311"
               , object="Incap311__Service_Type_Version__c"
               , connection="QA"
     )             
public class incap311__Base311_DupeSTVConfig {

	@ChoiceListType(multipleSelectionString = true, values = {
			@ChoiceListValue(value = "4tr5675765fryry75765765656576565675567565"), @ChoiceListValue(value = "Abandoned Bicycle"), @ChoiceListValue(value = "Abandoned Vehicles"), @ChoiceListValue(value = "Abandoned Vehicles Inspection"), @ChoiceListValue(value = "AETBB"), @ChoiceListValue(value = "AGKMF"), @ChoiceListValue(value = "AHNND"), @ChoiceListValue(value = "Aircraft Noise Disturbance"), @ChoiceListValue(value = "AJCJN"), @ChoiceListValue(value = "AJEQL"), @ChoiceListValue(value = "AKFOD"), @ChoiceListValue(value = "Alert Boston"), @ChoiceListValue(value = "Animal - Vaccination Investigation - DAS"), @ChoiceListValue(value = "Animal Found"), @ChoiceListValue(value = "Animal Generic Request"), @ChoiceListValue(value = "Animal Lost"), @ChoiceListValue(value = "ATSLM"), @ChoiceListValue(value = "aug_3_17"), @ChoiceListValue(value = "AWQPV"), @ChoiceListValue(value = "AXFGI"), @ChoiceListValue(value = "BCLB-Liquor License Complaint"), @ChoiceListValue(value = "BCPOP"), @ChoiceListValue(value = "Bed Bugs"), @ChoiceListValue(value = "Bicycle Issues"), @ChoiceListValue(value = "Big Buildings Work Order"), @ChoiceListValue(value = "Billing Complaint"), @ChoiceListValue(value = "Bird Infestation"), @ChoiceListValue(value = "BLMNE"), @ChoiceListValue(value = "BMZHJ"), @ChoiceListValue(value = "Boston Public Health Commission"), @ChoiceListValue(value = "BPHGV"), @ChoiceListValue(value = "Breathe Easy"), @ChoiceListValue(value = "Bridge Maintenance"), @ChoiceListValue(value = "BTPKY"), @ChoiceListValue(value = "Building Permit Inspection Request"), @ChoiceListValue(value = "Bulk by Requests"), @ChoiceListValue(value = "BWSC General Request"), @ChoiceListValue(value = "BYGSB"), @ChoiceListValue(value = "Capital Improvement Long Term"), @ChoiceListValue(value = "Catchbasin"), @ChoiceListValue(value = "CDBSI"), @ChoiceListValue(value = "CE Collection"), @ChoiceListValue(value = "CE Collection"), @ChoiceListValue(value = "Cemetery Maintenance Request"), @ChoiceListValue(value = "CGAWI"), @ChoiceListValue(value = "City Building Maintenance - EBS"), @ChoiceListValue(value = "CNXUS"), @ChoiceListValue(value = "Commercial Autobody Repair Shop"), @ChoiceListValue(value = "Configtesting"), @ChoiceListValue(value = "Contractor Complaints"), @ChoiceListValue(value = "Cross Metering - Sub-Metering"), @ChoiceListValue(value = "CUVJP"), @ChoiceListValue(value = "CYUVP"), @ChoiceListValue(value = "CZSAM"), @ChoiceListValue(value = "Dallas Tomorrow Fund - HOU"), @ChoiceListValue(value = "DBOKF"), @ChoiceListValue(value = "DBPLP"), @ChoiceListValue(value = "DDBCL"), @ChoiceListValue(value = "Dead Animal Pickup- SAN"), @ChoiceListValue(value = "Demo Service Type SM"), @ChoiceListValue(value = "Demotest"), @ChoiceListValue(value = "demo_test09"), @ChoiceListValue(value = "DHFZN"), @ChoiceListValue(value = "DHUMW"), @ChoiceListValue(value = "Disability General Request"), @ChoiceListValue(value = "DJLUY"), @ChoiceListValue(value = "DJYCR"), @ChoiceListValue(value = "DPRLO"), @ChoiceListValue(value = "DPYUJ"), @ChoiceListValue(value = "DSNQZ"), @ChoiceListValue(value = "Dumpster & Loading Noise Disturbances"), @ChoiceListValue(value = "DXCET"), @ChoiceListValue(value = "EAAZH"), @ChoiceListValue(value = "EAWOK"), @ChoiceListValue(value = "EBKDN"), @ChoiceListValue(value = "EFTVZ"), @ChoiceListValue(value = "EIQBQ"), @ChoiceListValue(value = "EJMCD"), @ChoiceListValue(value = "Electrical Permit Inspection Request"), @ChoiceListValue(value = "Emergency"), @ChoiceListValue(value = "Emergency Notification"), @ChoiceListValue(value = "Empty Litter Basket"), @ChoiceListValue(value = "EOHAJ"), @ChoiceListValue(value = "Equipment Repair"), @ChoiceListValue(value = "Erictest"), @ChoiceListValue(value = "erictest2"), @ChoiceListValue(value = "ESLIS"), @ChoiceListValue(value = "EVBTK"), @ChoiceListValue(value = "EWIMG"), @ChoiceListValue(value = "EZDZD"), @ChoiceListValue(value = "EZNDW"), @ChoiceListValue(value = "EZPSE"), @ChoiceListValue(value = "Failure to Deliver Proper Service"), @ChoiceListValue(value = "FCCS-Refunds"), @ChoiceListValue(value = "FCJVS"), @ChoiceListValue(value = "FDCGM"), @ChoiceListValue(value = "FDLZN"), @ChoiceListValue(value = "FFGHV"), @ChoiceListValue(value = "FFKCL"), @ChoiceListValue(value = "Fire Department Request"), @ChoiceListValue(value = "Fire Hydrant"), @ChoiceListValue(value = "Fire in Food Establishment"), @ChoiceListValue(value = "FIYTI"), @ChoiceListValue(value = "FJEQI"), @ChoiceListValue(value = "FJPZM"), @ChoiceListValue(value = "FKKUB"), @ChoiceListValue(value = "Food Alert - Confirmed"), @ChoiceListValue(value = "Food Alert - Unconfirmed"), @ChoiceListValue(value = "FPRFA"), @ChoiceListValue(value = "FQTRA"), @ChoiceListValue(value = "FRYWZ"), @ChoiceListValue(value = "FTOJI"), @ChoiceListValue(value = "FUXLX"), @ChoiceListValue(value = "GAPRT"), @ChoiceListValue(value = "Gas - Weights & Measures"), @ChoiceListValue(value = "GBCWI"), @ChoiceListValue(value = "GBPPP"), @ChoiceListValue(value = "GDJYU"), @ChoiceListValue(value = "GDMKE"), @ChoiceListValue(value = "GEEXI"), @ChoiceListValue(value = "General Building Complaint"), @ChoiceListValue(value = "General Comments For An Employee, Program or Policy"), @ChoiceListValue(value = "General Lighting Request"), @ChoiceListValue(value = "General Request"), @ChoiceListValue(value = "General School Request"), @ChoiceListValue(value = "General Transportation Issues"), @ChoiceListValue(value = "GKODW"), @ChoiceListValue(value = "GLQUH"), @ChoiceListValue(value = "GMBCD"), @ChoiceListValue(value = "GMLFY"), @ChoiceListValue(value = "GNJYI"), @ChoiceListValue(value = "GPCFD"), @ChoiceListValue(value = "GQKRW"), @ChoiceListValue(value = "Graffiti"), @ChoiceListValue(value = "Graffiti Removal"), @ChoiceListValue(value = "Ground Maintenance"), @ChoiceListValue(value = "GSKYF"), @ChoiceListValue(value = "GUZIM"), @ChoiceListValue(value = "GYBXS"), @ChoiceListValue(value = "GZNWT"), @ChoiceListValue(value = "harsha-test"), @ChoiceListValue(value = "HCD-Maintenance Structure"), @ChoiceListValue(value = "HCD-Systems"), @ChoiceListValue(value = "HDLJV"), @ChoiceListValue(value = "Heat - Excessive, Insufficient"), @ChoiceListValue(value = "HFUVT"), @ChoiceListValue(value = "HICTG"), @ChoiceListValue(value = "HIDVP"), @ChoiceListValue(value = "Highway Maintenance"), @ChoiceListValue(value = "HKTJT"), @ChoiceListValue(value = "HLRNI"), @ChoiceListValue(value = "HLTH-Animal Aggressive Animal"), @ChoiceListValue(value = "HLTH-Animal Attack Against Animal"), @ChoiceListValue(value = "HLTH-Animal Attack Against Human"), @ChoiceListValue(value = "HLTH-Animal Barking Dog"), @ChoiceListValue(value = "HLTH-Animal Bite Pickup"), @ChoiceListValue(value = "HLTH-Animal Dead Animal Pick Up, Death of a Pet (Tracking)"), @ChoiceListValue(value = "HLTH-Animal Domestic Animal Trap or Capture Request"), @ChoiceListValue(value = "HLTH-Animal Failure to Restrain Animal, Known Owner/Known Address"), @ChoiceListValue(value = "HLTH-Animal Healthy Unwanted Animals (Tracking)"), @ChoiceListValue(value = "HLTH-Animal In Danger/Injured/Abused/Neglected"), @ChoiceListValue(value = "HLTH-Animal Inspection/Follow-up"), @ChoiceListValue(value = "HLTH-Animal Police/Fire/Sheriff/City Work Crew Standby"), @ChoiceListValue(value = "HLTH-Animal Running At Large/Stray (Tracking)"), @ChoiceListValue(value = "HLTH-Animal Search and Seizure"), @ChoiceListValue(value = "HLTH-Animal Stray Held"), @ChoiceListValue(value = "HLTH-Animal Trapped In Vacant Building"), @ChoiceListValue(value = "HLTH-Animal Unsanitary Conditions"), @ChoiceListValue(value = "HLTH-Animal Wildlife Complaint"), @ChoiceListValue(value = "HLTH-Animal-Dead Animal Pickup-Wildlife or Stray"), @ChoiceListValue(value = "HLTH-EV Dust"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Emergency Sewer Investigation"), @ChoiceListValue(value = "HLTH-EV Institutional Food Facility"), @ChoiceListValue(value = "HLTH-EV Mosquito Surveillance"), @ChoiceListValue(value = "HLTH-EV Noise"), @ChoiceListValue(value = "HLTH-EV Odor"), @ChoiceListValue(value = "HLTH-EV Public Swimming Pool/Spa Complaint"), @ChoiceListValue(value = "HLTH-EV Report of Retail Sale of Illegal Synthetic Drugs"), @ChoiceListValue(value = "HLTH-EV Stagnant Water"), @ChoiceListValue(value = "HLTH-EV Tattoo Facility"), @ChoiceListValue(value = "HLTH-Food Borne Illness Alleged"), @ChoiceListValue(value = "HLTH-Food Facility Complaint"), @ChoiceListValue(value = "HOC test"), @ChoiceListValue(value = "HP Sign Removal"), @ChoiceListValue(value = "HP Sign Removal"), @ChoiceListValue(value = "HP Sign Repair"), @ChoiceListValue(value = "HP Sign Request"), @ChoiceListValue(value = "HQLZA"), @ChoiceListValue(value = "HVAPU"), @ChoiceListValue(value = "HWEUI"), @ChoiceListValue(value = "HWIJC"), @ChoiceListValue(value = "HZGPC"), @ChoiceListValue(value = "ICCPG"), @ChoiceListValue(value = "IDYIZ"), @ChoiceListValue(value = "IENER"), @ChoiceListValue(value = "IFOPG"), @ChoiceListValue(value = "IGFRU"), @ChoiceListValue(value = "IIZRW"), @ChoiceListValue(value = "Illegal Dumping"), @ChoiceListValue(value = "Illegal Dumping new"), @ChoiceListValue(value = "Illegal Posting of Signs"), @ChoiceListValue(value = "Illegal Vending"), @ChoiceListValue(value = "Improper Storage of Trash (Barrels)"), @ChoiceListValue(value = "Incap Generic"), @ChoiceListValue(value = "Incap inquiry"), @ChoiceListValue(value = "INMMQ"), @ChoiceListValue(value = "INPYV"), @ChoiceListValue(value = "Inquiry"), @ChoiceListValue(value = "Install New Lighting"), @ChoiceListValue(value = "IYATY"), @ChoiceListValue(value = "IYBAV"), @ChoiceListValue(value = "JBNGT"), @ChoiceListValue(value = "JDDBV"), @ChoiceListValue(value = "JQEWI"), @ChoiceListValue(value = "JRJTZ"), @ChoiceListValue(value = "JWOXV"), @ChoiceListValue(value = "JXFEF"), @ChoiceListValue(value = "JZAEY"), @ChoiceListValue(value = "KARJS"), @ChoiceListValue(value = "KAUBR"), @ChoiceListValue(value = "KDHLO"), @ChoiceListValue(value = "KFVVI"), @ChoiceListValue(value = "KHCRP"), @ChoiceListValue(value = "KKBAS"), @ChoiceListValue(value = "KMVAH"), @ChoiceListValue(value = "KOCWX"), @ChoiceListValue(value = "KULQE"), @ChoiceListValue(value = "KXTGC"), @ChoiceListValue(value = "KZXAS"), @ChoiceListValue(value = "LCCKD"), @ChoiceListValue(value = "Lead Paint"), @ChoiceListValue(value = "Litter Basket Maintenance"), @ChoiceListValue(value = "LIVKY"), @ChoiceListValue(value = "LKCNT"), @ChoiceListValue(value = "LQDKY"), @ChoiceListValue(value = "LSJQM"), @ChoiceListValue(value = "LSYKZ"), @ChoiceListValue(value = "LUODZ"), @ChoiceListValue(value = "LWAFH"), @ChoiceListValue(value = "LXBGC"), @ChoiceListValue(value = "LZWYX"), @ChoiceListValue(value = "LZYCY"), @ChoiceListValue(value = "Major System Failure"), @ChoiceListValue(value = "MBTA Request"), @ChoiceListValue(value = "MCQWE"), @ChoiceListValue(value = "Mechanical Permit Inspection Request"), @ChoiceListValue(value = "MGIEE"), @ChoiceListValue(value = "Misc. Snow Complaint"), @ChoiceListValue(value = "Missed Trash/Recycling/Yard Waste/Bulk Item"), @ChoiceListValue(value = "Missing/Damaged Sign Repair"), @ChoiceListValue(value = "MMQVX"), @ChoiceListValue(value = "MOPNZ"), @ChoiceListValue(value = "MQWUF"), @ChoiceListValue(value = "MRRTL"), @ChoiceListValue(value = "MUSRG"), @ChoiceListValue(value = "MVRWV"), @ChoiceListValue(value = "MWAFO"), @ChoiceListValue(value = "MXAQB"), @ChoiceListValue(value = "MXOZJ"), @ChoiceListValue(value = "MYGAK"), @ChoiceListValue(value = "MyServicename24"), @ChoiceListValue(value = "NAZFS"), @ChoiceListValue(value = "NCBOT"), @ChoiceListValue(value = "NDDExotic Pet"), @ChoiceListValue(value = "NDYUZ"), @ChoiceListValue(value = "Needle Removal Request"), @ChoiceListValue(value = "New Tree Requests"), @ChoiceListValue(value = "News Boxes"), @ChoiceListValue(value = "News Boxes"), @ChoiceListValue(value = "NMFGB"), @ChoiceListValue(value = "NMRXD"), @ChoiceListValue(value = "NMSSX"), @ChoiceListValue(value = "NMYMJ"), @ChoiceListValue(value = "No Utilities - Electricity"), @ChoiceListValue(value = "No Utilities - Flood"), @ChoiceListValue(value = "No Utilities - No Water"), @ChoiceListValue(value = "No Utilities - Sewer"), @ChoiceListValue(value = "No-Tow Complaint Confirmation"), @ChoiceListValue(value = "NSQCA"), @ChoiceListValue(value = "NUNCD"), @ChoiceListValue(value = "NXRDD"), @ChoiceListValue(value = "OCBKE"), @ChoiceListValue(value = "OCGFF"), @ChoiceListValue(value = "OFHTB"), @ChoiceListValue(value = "OFKIQ"), @ChoiceListValue(value = "OHGVZ"), @ChoiceListValue(value = "Oil Truck - Weights & Measures"), @ChoiceListValue(value = "OJMKM"), @ChoiceListValue(value = "ONHCV"), @ChoiceListValue(value = "OOXZB"), @ChoiceListValue(value = "ORYAT"), @ChoiceListValue(value = "OSYCK"), @ChoiceListValue(value = "Other - Weights & Measures"), @ChoiceListValue(value = "OTPEX"), @ChoiceListValue(value = "OTWVR"), @ChoiceListValue(value = "Overcrowding"), @ChoiceListValue(value = "Overgrown Vegetation"), @ChoiceListValue(value = "Park Carpentry"), @ChoiceListValue(value = "Park Graffiti"), @ChoiceListValue(value = "Park Horticulture Service"), @ChoiceListValue(value = "Park Improvement Requests"), @ChoiceListValue(value = "Park Painting"), @ChoiceListValue(value = "Park Painting Test"), @ChoiceListValue(value = "Park Plumbing"), @ChoiceListValue(value = "Park Welding"), @ChoiceListValue(value = "Parking Enforcement"), @ChoiceListValue(value = "Parking Meter Repairs"), @ChoiceListValue(value = "Parking on Front/Back Yards (Illegal Parking)"), @ChoiceListValue(value = "Parks General Request"), @ChoiceListValue(value = "Parks Lighting/Electrical Issues"), @ChoiceListValue(value = "Pavement Marking Inspection"), @ChoiceListValue(value = "Pavement Marking Maintenance"), @ChoiceListValue(value = "PEBYG"), @ChoiceListValue(value = "PEXID"), @ChoiceListValue(value = "PGRAS"), @ChoiceListValue(value = "PHLYH"), @ChoiceListValue(value = "PHSAW"), @ChoiceListValue(value = "PHUFD"), @ChoiceListValue(value = "PIBAF"), @ChoiceListValue(value = "Pick up Dead Animal"), @ChoiceListValue(value = "Pickup Clear Conduit"), @ChoiceListValue(value = "PJQOA"), @ChoiceListValue(value = "PJZBH"), @ChoiceListValue(value = "PNBKY"), @ChoiceListValue(value = "PONXN"), @ChoiceListValue(value = "Poor Ventilation"), @ChoiceListValue(value = "PPUKX"), @ChoiceListValue(value = "Price Issues - Weights & Measures"), @ChoiceListValue(value = "PRO-SR-AZNJ9297"), @ChoiceListValue(value = "PRO-SR-BPFE9680"), @ChoiceListValue(value = "PRO-SR-BSHB8044"), @ChoiceListValue(value = "PRO-SR-BYGJ1375"), @ChoiceListValue(value = "PRO-SR-BYIV9237"), @ChoiceListValue(value = "PRO-SR-CXLI6978"), @ChoiceListValue(value = "PRO-SR-DFGW6615"), @ChoiceListValue(value = "PRO-SR-EHGT6368"), @ChoiceListValue(value = "PRO-SR-GGPR0279"), @ChoiceListValue(value = "PRO-SR-GMFA4611"), @ChoiceListValue(value = "PRO-SR-GUKN3634"), @ChoiceListValue(value = "PRO-SR-HDSU2960"), @ChoiceListValue(value = "PRO-SR-HYVO3098"), @ChoiceListValue(value = "PRO-SR-ISGS6063"), @ChoiceListValue(value = "PRO-SR-JJBA8223"), @ChoiceListValue(value = "PRO-SR-KOKE4538"), @ChoiceListValue(value = "PRO-SR-LZNA3696"), @ChoiceListValue(value = "PRO-SR-NBFA6932"), @ChoiceListValue(value = "PRO-SR-NIXO1819"), @ChoiceListValue(value = "PRO-SR-NLEW4169"), @ChoiceListValue(value = "PRO-SR-NQIZ0791"), @ChoiceListValue(value = "PRO-SR-NXIU2374"), @ChoiceListValue(value = "PRO-SR-OIQN0947"), @ChoiceListValue(value = "PRO-SR-PXUZ3685"), @ChoiceListValue(value = "PRO-SR-QDUL1123"), @ChoiceListValue(value = "PRO-SR-QTPE5704"), @ChoiceListValue(value = "PRO-SR-RLEJ4439"), @ChoiceListValue(value = "PRO-SR-RRGN8096"), @ChoiceListValue(value = "PRO-SR-SCHV1837"), @ChoiceListValue(value = "PRO-SR-SIQZ2900"), @ChoiceListValue(value = "PRO-SR-SKIC0400"), @ChoiceListValue(value = "PRO-SR-TCSA1788"), @ChoiceListValue(value = "PRO-SR-TMCD8351"), @ChoiceListValue(value = "PRO-SR-TYCO2297"), @ChoiceListValue(value = "PRO-SR-UEFD8639"), @ChoiceListValue(value = "PRO-SR-VHCR3868"), @ChoiceListValue(value = "PRO-SR-VHYU4449"), @ChoiceListValue(value = "PRO-SR-VOSU5288"), @ChoiceListValue(value = "PRO-SR-WDDJ0837"), @ChoiceListValue(value = "PRO-SR-WQDX6644"), @ChoiceListValue(value = "PRO-SR-WYRH4012"), @ChoiceListValue(value = "PRO-SR-XLHD6143"), @ChoiceListValue(value = "PRO-SR-XZKD9296"), @ChoiceListValue(value = "PRO-SR-YEOD0918"), @ChoiceListValue(value = "PRO-SR-YHFI1770"), @ChoiceListValue(value = "PRO-SR-YTCQ2966"), @ChoiceListValue(value = "Protection of Adjoining Property"), @ChoiceListValue(value = "Provar - Schedule - SR"), @ChoiceListValue(value = "Provar Reg Date Check"), @ChoiceListValue(value = "Provar Regression RWH"), @ChoiceListValue(value = "Provar Regression Test SR"), @ChoiceListValue(value = "Provar Regression with RH"), @ChoiceListValue(value = "Provar Regression WRH"), @ChoiceListValue(value = "Provar Regression WRWH"), @ChoiceListValue(value = "Provar System Gen"), @ChoiceListValue(value = "Provar-Bus-Hours"), @ChoiceListValue(value = "Provar-POC-1"), @ChoiceListValue(value = "Provar-POC-2"), @ChoiceListValue(value = "Provar-POC-3"), @ChoiceListValue(value = "Provar-POC-4"), @ChoiceListValue(value = "Provar-POC-5"), @ChoiceListValue(value = "Provar-Service-Question"), @ChoiceListValue(value = "PRQAI"), @ChoiceListValue(value = "PRYMB"), @ChoiceListValue(value = "PTUCC"), @ChoiceListValue(value = "Public Works General Request"), @ChoiceListValue(value = "QBCYG"), @ChoiceListValue(value = "QBMJN"), @ChoiceListValue(value = "QECTN"), @ChoiceListValue(value = "QEWKH"), @ChoiceListValue(value = "QHAHM"), @ChoiceListValue(value = "QPSSK"), @ChoiceListValue(value = "QVUTV"), @ChoiceListValue(value = "QWJNV"), @ChoiceListValue(value = "QXFER"), @ChoiceListValue(value = "Rat Bite"), @ChoiceListValue(value = "RBCWL"), @ChoiceListValue(value = "RDYKH"), @ChoiceListValue(value = "Recycling Cart Inquiry"), @ChoiceListValue(value = "Recycling Cart Inquiry new"), @ChoiceListValue(value = "Recycling Cart Return"), @ChoiceListValue(value = "Rental Unit Delivery Conditions"), @ChoiceListValue(value = "Request for Litter Basket Installation"), @ChoiceListValue(value = "Request for Pothole Repair"), @ChoiceListValue(value = "Request for Recycling Cart"), @ChoiceListValue(value = "Request for Snow Plowing"), @ChoiceListValue(value = "Request for Snow Plowing (Emergency Responder)"), @ChoiceListValue(value = "Requests for Street Cleaning"), @ChoiceListValue(value = "Reweigh/Short Measure - Weights & Measures"), @ChoiceListValue(value = "RFEYZ"), @ChoiceListValue(value = "RKHMZ"), @ChoiceListValue(value = "RLUZU"), @ChoiceListValue(value = "RNOMD"), @ChoiceListValue(value = "RNRJT"), @ChoiceListValue(value = "Roadway Repair"), @ChoiceListValue(value = "Rodent Activity"), @ChoiceListValue(value = "Rooftop & Mechanical Disturbances"), @ChoiceListValue(value = "RSKYZ"), @ChoiceListValue(value = "RWLJD"), @ChoiceListValue(value = "RZHDV"), @ChoiceListValue(value = "SajivTest-Aug-01"), @ChoiceListValue(value = "Scale - Weights & Measures"), @ChoiceListValue(value = "Schedulable SR-Harsha"), @ChoiceListValue(value = "Schedulable-Item SR"), @ChoiceListValue(value = "Schedule a Bulk Item Pickup"), @ChoiceListValue(value = "School Administration"), @ChoiceListValue(value = "SEANTESTA"), @ChoiceListValue(value = "SEANTESTB"), @ChoiceListValue(value = "Service_Name"), @ChoiceListValue(value = "SHDKZ"), @ChoiceListValue(value = "Sideguard - Weights & Measures"), @ChoiceListValue(value = "Sidewalk Cover / Manhole"), @ChoiceListValue(value = "Sidewalk Repair"), @ChoiceListValue(value = "Snow Buildup Removal (Emergency Agency)"), @ChoiceListValue(value = "Snow Removal"), @ChoiceListValue(value = "Space Savers"), @ChoiceListValue(value = "Squalid Living Conditions/Hoarding"), @ChoiceListValue(value = "SSFJE"), @ChoiceListValue(value = "Stagnant Water"), @ChoiceListValue(value = "STESTA02"), @ChoiceListValue(value = "Sticker Request"), @ChoiceListValue(value = "Street Light Knock Downs"), @ChoiceListValue(value = "Street Light Outage test"), @ChoiceListValue(value = "Street Light Outages"), @ChoiceListValue(value = "Street Light Poles Highway"), @ChoiceListValue(value = "SXCOW"), @ChoiceListValue(value = "SZEKJ"), @ChoiceListValue(value = "SZTBR"), @ChoiceListValue(value = "Taxi - Transportation Complaint - AVI"), @ChoiceListValue(value = "Taxi Meter - Weights & Measures"), @ChoiceListValue(value = "Test"), @ChoiceListValue(value = "test"), @ChoiceListValue(value = "test"), @ChoiceListValue(value = "test"), @ChoiceListValue(value = "test 1234567"), @ChoiceListValue(value = "test 343"), @ChoiceListValue(value = "test 42"), @ChoiceListValue(value = "test 456"), @ChoiceListValue(value = "test 55"), @ChoiceListValue(value = "Test 564"), @ChoiceListValue(value = "test 765"), @ChoiceListValue(value = "test 7655"), @ChoiceListValue(value = "test 9876"), @ChoiceListValue(value = "Test for Transfers"), @ChoiceListValue(value = "Test Oct 2017"), @ChoiceListValue(value = "test recycling cart inquiry"), @ChoiceListValue(value = "Test Upgrade Existing Lighting"), @ChoiceListValue(value = "Test Version1"), @ChoiceListValue(value = "Test-03-20_1"), @ChoiceListValue(value = "Test-03-20_2"), @ChoiceListValue(value = "Test-May-07-01"), @ChoiceListValue(value = "TEST-PROVAR-JUL-POC-1"), @ChoiceListValue(value = "TEST-PROVAR-JUL-POC-1"), @ChoiceListValue(value = "TEST-PROVAR-JUL-POC-1"), @ChoiceListValue(value = "TEST-PROVAR-JUL-POC-1"), @ChoiceListValue(value = "TEST-PROVAR-JUL-POC-1"), @ChoiceListValue(value = "TEST-PROVAR-JUL-POC-1"), @ChoiceListValue(value = "Test-S-M-2017-03-01-01"), @ChoiceListValue(value = "Test-Service-Name-Jul-01"), @ChoiceListValue(value = "Test-Service-Type-J-28-01"), @ChoiceListValue(value = "TEST-ST-10-JUL-01"), @ChoiceListValue(value = "TEST-ST-10-JUL-02"), @ChoiceListValue(value = "test09"), @ChoiceListValue(value = "test1223"), @ChoiceListValue(value = "test129"), @ChoiceListValue(value = "test2"), @ChoiceListValue(value = "test234"), @ChoiceListValue(value = "test3"), @ChoiceListValue(value = "test433"), @ChoiceListValue(value = "test444"), @ChoiceListValue(value = "test521"), @ChoiceListValue(value = "test521"), @ChoiceListValue(value = "test6"), @ChoiceListValue(value = "test774"), @ChoiceListValue(value = "test89"), @ChoiceListValue(value = "test9182"), @ChoiceListValue(value = "TestServiceName"), @ChoiceListValue(value = "testTest _78"), @ChoiceListValue(value = "TestTree Emergency"), @ChoiceListValue(value = "test_0"), @ChoiceListValue(value = "test_1234"), @ChoiceListValue(value = "test_19"), @ChoiceListValue(value = "Test_21_3"), @ChoiceListValue(value = "test_432"), @ChoiceListValue(value = "test_654"), @ChoiceListValue(value = "test_654"), @ChoiceListValue(value = "test_87"), @ChoiceListValue(value = "test_98"), @ChoiceListValue(value = "test_98"), @ChoiceListValue(value = "test_demo"), @ChoiceListValue(value = "test_demo1"), @ChoiceListValue(value = "test_demo1 service name"), @ChoiceListValue(value = "THJBM"), @ChoiceListValue(value = "Traffic Signal Inspection"), @ChoiceListValue(value = "Traffic Signal Repair"), @ChoiceListValue(value = "Transportation General Request"), @ChoiceListValue(value = "Tree Emergencies"), @ChoiceListValue(value = "Tree Emergency"), @ChoiceListValue(value = "Tree Emergency new"), @ChoiceListValue(value = "Tree in Park"), @ChoiceListValue(value = "Tree Maintenance Requests"), @ChoiceListValue(value = "TSTVB"), @ChoiceListValue(value = "ULYFG"), @ChoiceListValue(value = "Unsafe Dangerous Conditions"), @ChoiceListValue(value = "Unsanitary Conditions - Camps"), @ChoiceListValue(value = "Unsanitary Conditions - Employees"), @ChoiceListValue(value = "Unsanitary Conditions - Establishment"), @ChoiceListValue(value = "Unsanitary Conditions - Food"), @ChoiceListValue(value = "Unsanitary Conditions - Pools"), @ChoiceListValue(value = "Unsanitary Trash Conditions"), @ChoiceListValue(value = "Unsatisfactory Living Conditions"), @ChoiceListValue(value = "Unshoveled Sidewalk"), @ChoiceListValue(value = "Upgrade Existing Lighting"), @ChoiceListValue(value = "Upgrade Existing Lighting"), @ChoiceListValue(value = "UQJQS"), @ChoiceListValue(value = "URUPP"), @ChoiceListValue(value = "Utility Casting Repair"), @ChoiceListValue(value = "UTJGI"), @ChoiceListValue(value = "UTLAA"), @ChoiceListValue(value = "UTPLW"), @ChoiceListValue(value = "UUHWC"), @ChoiceListValue(value = "UXKHA"), @ChoiceListValue(value = "Vacant Lot - Land Not Maintained"), @ChoiceListValue(value = "VHQRX"), @ChoiceListValue(value = "VJHHN"), @ChoiceListValue(value = "VNICA"), @ChoiceListValue(value = "VPEQY"), @ChoiceListValue(value = "VUXSB"), @ChoiceListValue(value = "WAOQB"), @ChoiceListValue(value = "WBAOT"), @ChoiceListValue(value = "WFOAI"), @ChoiceListValue(value = "WFYGO"), @ChoiceListValue(value = "WIUZO"), @ChoiceListValue(value = "WJJJT"), @ChoiceListValue(value = "WMGVC"), @ChoiceListValue(value = "WNZCP"), @ChoiceListValue(value = "WOODY"), @ChoiceListValue(value = "Work Hours-Loud Noise Complaints"), @ChoiceListValue(value = "WPFWS"), @ChoiceListValue(value = "WRPID"), @ChoiceListValue(value = "WUSMN"), @ChoiceListValue(value = "WVDQB"), @ChoiceListValue(value = "WW-Sewer Water In Basement"), @ChoiceListValue(value = "WW-Water Leak (Exterior)"), @ChoiceListValue(value = "WXUSG"), @ChoiceListValue(value = "XCAMR"), @ChoiceListValue(value = "XCZSN"), @ChoiceListValue(value = "XDNGA"), @ChoiceListValue(value = "XDVOC"), @ChoiceListValue(value = "XDWEG"), @ChoiceListValue(value = "XEKXW"), @ChoiceListValue(value = "XKZCS"), @ChoiceListValue(value = "XYGQF"), @ChoiceListValue(value = "YCDDY"), @ChoiceListValue(value = "YGSSK"), @ChoiceListValue(value = "YHDSO"), @ChoiceListValue(value = "YHQZK"), @ChoiceListValue(value = "YLJTO"), @ChoiceListValue(value = "YNQGZ"), @ChoiceListValue(value = "YNVGM"), @ChoiceListValue(value = "YOYFI"), @ChoiceListValue(value = "YPLTZ"), @ChoiceListValue(value = "YUJLP"), @ChoiceListValue(value = "YUQES"), @ChoiceListValue(value = "YWXNT"), @ChoiceListValue(value = "YYUDR"), @ChoiceListValue(value = "YZXVD"), @ChoiceListValue(value = "ZFTSG"), @ChoiceListValue(value = "ZGKLE"), @ChoiceListValue(value = "ZQGYM"), @ChoiceListValue(value = "ZRKKR"), @ChoiceListValue(value = "ZUGAZ"), @ChoiceListValue(value = "ZUJVE"), @ChoiceListValue(value = "ZWMAW"), @ChoiceListValue(value = "ZZKYD"), @ChoiceListValue(value = "ZZMUZ") })
	@FindBy(xpath = "//tr/td[1]/select")
	public WebElement availableTypesSelectProvarRegression;
	@ChoiceListType(multipleSelectionString = true, values = {
			@ChoiceListValue(value = "4tr5675765fryry75765765656576565675567565"),
			@ChoiceListValue(value = "Abandoned Bicycle"), @ChoiceListValue(value = "Abandoned Vehicles"),
			@ChoiceListValue(value = "Abandoned Vehicles Inspection"), @ChoiceListValue(value = "AETBB"),
			@ChoiceListValue(value = "AGKMF"), @ChoiceListValue(value = "AHNND"),
			@ChoiceListValue(value = "Aircraft Noise Disturbance"), @ChoiceListValue(value = "AJCJN"),
			@ChoiceListValue(value = "AJEQL"), @ChoiceListValue(value = "AKFOD"),
			@ChoiceListValue(value = "Alert Boston"),
			@ChoiceListValue(value = "Animal - Vaccination Investigation - DAS"),
			@ChoiceListValue(value = "Animal Found"), @ChoiceListValue(value = "Animal Generic Request"),
			@ChoiceListValue(value = "Animal Lost"), @ChoiceListValue(value = "ATSLM"),
			@ChoiceListValue(value = "aug_3_17"), @ChoiceListValue(value = "AWQPV"), @ChoiceListValue(value = "AXFGI"),
			@ChoiceListValue(value = "BCLB-Liquor License Complaint"), @ChoiceListValue(value = "BCPOP"),
			@ChoiceListValue(value = "Bed Bugs"), @ChoiceListValue(value = "Bicycle Issues"),
			@ChoiceListValue(value = "Big Buildings Work Order"), @ChoiceListValue(value = "Billing Complaint"),
			@ChoiceListValue(value = "Bird Infestation"), @ChoiceListValue(value = "BLMNE"),
			@ChoiceListValue(value = "BMZHJ"), @ChoiceListValue(value = "Boston Public Health Commission"),
			@ChoiceListValue(value = "BPHGV"), @ChoiceListValue(value = "Breathe Easy"),
			@ChoiceListValue(value = "Bridge Maintenance"), @ChoiceListValue(value = "BTPKY"),
			@ChoiceListValue(value = "Building Permit Inspection Request"),
			@ChoiceListValue(value = "Bulk by Requests"), @ChoiceListValue(value = "BWSC General Request"),
			@ChoiceListValue(value = "BYGSB"), @ChoiceListValue(value = "Capital Improvement Long Term"),
			@ChoiceListValue(value = "Catchbasin"), @ChoiceListValue(value = "CDBSI"),
			@ChoiceListValue(value = "CE Collection"), @ChoiceListValue(value = "CE Collection"),
			@ChoiceListValue(value = "Cemetery Maintenance Request"), @ChoiceListValue(value = "CGAWI"),
			@ChoiceListValue(value = "City Building Maintenance - EBS"), @ChoiceListValue(value = "CNXUS"),
			@ChoiceListValue(value = "Commercial Autobody Repair Shop"), @ChoiceListValue(value = "Configtesting"),
			@ChoiceListValue(value = "Contractor Complaints"),
			@ChoiceListValue(value = "Cross Metering - Sub-Metering"), @ChoiceListValue(value = "CUVJP"),
			@ChoiceListValue(value = "CYUVP"), @ChoiceListValue(value = "CZSAM"),
			@ChoiceListValue(value = "Dallas Tomorrow Fund - HOU"), @ChoiceListValue(value = "DBOKF"),
			@ChoiceListValue(value = "DBPLP"), @ChoiceListValue(value = "DDBCL"),
			@ChoiceListValue(value = "Dead Animal Pickup- SAN"), @ChoiceListValue(value = "Demo Service Type SM"),
			@ChoiceListValue(value = "Demotest"), @ChoiceListValue(value = "demo_test09"),
			@ChoiceListValue(value = "DHFZN"), @ChoiceListValue(value = "DHUMW"),
			@ChoiceListValue(value = "Disability General Request"), @ChoiceListValue(value = "DJLUY"),
			@ChoiceListValue(value = "DJYCR"), @ChoiceListValue(value = "DPRLO"), @ChoiceListValue(value = "DPYUJ"),
			@ChoiceListValue(value = "DSNQZ"), @ChoiceListValue(value = "Dumpster & Loading Noise Disturbances"),
			@ChoiceListValue(value = "DXCET"), @ChoiceListValue(value = "EAAZH"), @ChoiceListValue(value = "EAWOK"),
			@ChoiceListValue(value = "EBKDN"), @ChoiceListValue(value = "EFTVZ"), @ChoiceListValue(value = "EIQBQ"),
			@ChoiceListValue(value = "EJMCD"), @ChoiceListValue(value = "Electrical Permit Inspection Request"),
			@ChoiceListValue(value = "Emergency"), @ChoiceListValue(value = "Emergency Notification"),
			@ChoiceListValue(value = "Empty Litter Basket"), @ChoiceListValue(value = "EOHAJ"),
			@ChoiceListValue(value = "Equipment Repair"), @ChoiceListValue(value = "Erictest"),
			@ChoiceListValue(value = "erictest2"), @ChoiceListValue(value = "ESLIS"), @ChoiceListValue(value = "EVBTK"),
			@ChoiceListValue(value = "EWIMG"), @ChoiceListValue(value = "EZDZD"), @ChoiceListValue(value = "EZNDW"),
			@ChoiceListValue(value = "EZPSE"), @ChoiceListValue(value = "Failure to Deliver Proper Service"),
			@ChoiceListValue(value = "FCCS-Refunds"), @ChoiceListValue(value = "FCJVS"),
			@ChoiceListValue(value = "FDCGM"), @ChoiceListValue(value = "FDLZN"), @ChoiceListValue(value = "FFGHV"),
			@ChoiceListValue(value = "FFKCL"), @ChoiceListValue(value = "Fire Department Request"),
			@ChoiceListValue(value = "Fire Hydrant"), @ChoiceListValue(value = "Fire in Food Establishment"),
			@ChoiceListValue(value = "FIYTI"), @ChoiceListValue(value = "FJEQI"), @ChoiceListValue(value = "FJPZM"),
			@ChoiceListValue(value = "FKKUB"), @ChoiceListValue(value = "Food Alert - Confirmed"),
			@ChoiceListValue(value = "Food Alert - Unconfirmed"), @ChoiceListValue(value = "FPRFA"),
			@ChoiceListValue(value = "FQTRA"), @ChoiceListValue(value = "FRYWZ"), @ChoiceListValue(value = "FTOJI"),
			@ChoiceListValue(value = "FUXLX"), @ChoiceListValue(value = "GAPRT"),
			@ChoiceListValue(value = "Gas - Weights & Measures"), @ChoiceListValue(value = "GBCWI"),
			@ChoiceListValue(value = "GBPPP"), @ChoiceListValue(value = "GDJYU"), @ChoiceListValue(value = "GDMKE"),
			@ChoiceListValue(value = "GEEXI"), @ChoiceListValue(value = "General Building Complaint"),
			@ChoiceListValue(value = "General Comments For An Employee, Program or Policy"),
			@ChoiceListValue(value = "General Lighting Request"), @ChoiceListValue(value = "General Request"),
			@ChoiceListValue(value = "General School Request"),
			@ChoiceListValue(value = "General Transportation Issues"), @ChoiceListValue(value = "GKODW"),
			@ChoiceListValue(value = "GLQUH"), @ChoiceListValue(value = "GMBCD"), @ChoiceListValue(value = "GMLFY"),
			@ChoiceListValue(value = "GNJYI"), @ChoiceListValue(value = "GPCFD"), @ChoiceListValue(value = "GQKRW"),
			@ChoiceListValue(value = "Graffiti"), @ChoiceListValue(value = "Graffiti Removal"),
			@ChoiceListValue(value = "Ground Maintenance"), @ChoiceListValue(value = "GSKYF"),
			@ChoiceListValue(value = "GUZIM"), @ChoiceListValue(value = "GYBXS"), @ChoiceListValue(value = "GZNWT"),
			@ChoiceListValue(value = "harsha-test"), @ChoiceListValue(value = "HCD-Maintenance Structure"),
			@ChoiceListValue(value = "HCD-Systems"), @ChoiceListValue(value = "HDLJV"),
			@ChoiceListValue(value = "Heat - Excessive, Insufficient"), @ChoiceListValue(value = "HFUVT"),
			@ChoiceListValue(value = "HICTG"), @ChoiceListValue(value = "HIDVP"),
			@ChoiceListValue(value = "Highway Maintenance"), @ChoiceListValue(value = "HKTJT"),
			@ChoiceListValue(value = "HLRNI"), @ChoiceListValue(value = "HLTH-Animal Aggressive Animal"),
			@ChoiceListValue(value = "HLTH-Animal Attack Against Animal"),
			@ChoiceListValue(value = "HLTH-Animal Attack Against Human"),
			@ChoiceListValue(value = "HLTH-Animal Barking Dog"), @ChoiceListValue(value = "HLTH-Animal Bite Pickup"),
			@ChoiceListValue(value = "HLTH-Animal Dead Animal Pick Up, Death of a Pet (Tracking)"),
			@ChoiceListValue(value = "HLTH-Animal Domestic Animal Trap or Capture Request"),
			@ChoiceListValue(value = "HLTH-Animal Failure to Restrain Animal, Known Owner/Known Address"),
			@ChoiceListValue(value = "HLTH-Animal Healthy Unwanted Animals (Tracking)"),
			@ChoiceListValue(value = "HLTH-Animal In Danger/Injured/Abused/Neglected"),
			@ChoiceListValue(value = "HLTH-Animal Inspection/Follow-up"),
			@ChoiceListValue(value = "HLTH-Animal Police/Fire/Sheriff/City Work Crew Standby"),
			@ChoiceListValue(value = "HLTH-Animal Running At Large/Stray (Tracking)"),
			@ChoiceListValue(value = "HLTH-Animal Search and Seizure"),
			@ChoiceListValue(value = "HLTH-Animal Stray Held"),
			@ChoiceListValue(value = "HLTH-Animal Trapped In Vacant Building"),
			@ChoiceListValue(value = "HLTH-Animal Unsanitary Conditions"),
			@ChoiceListValue(value = "HLTH-Animal Wildlife Complaint"),
			@ChoiceListValue(value = "HLTH-Animal-Dead Animal Pickup-Wildlife or Stray"),
			@ChoiceListValue(value = "HLTH-EV Dust"), @ChoiceListValue(value = "HLTH-EV Dust-POC"),
			@ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"),
			@ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"),
			@ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"),
			@ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"),
			@ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"),
			@ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"),
			@ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"),
			@ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"),
			@ChoiceListValue(value = "HLTH-EV Dust-POC"), @ChoiceListValue(value = "HLTH-EV Dust-POC"),
			@ChoiceListValue(value = "HLTH-EV Emergency Sewer Investigation"),
			@ChoiceListValue(value = "HLTH-EV Institutional Food Facility"),
			@ChoiceListValue(value = "HLTH-EV Mosquito Surveillance"), @ChoiceListValue(value = "HLTH-EV Noise"),
			@ChoiceListValue(value = "HLTH-EV Odor"),
			@ChoiceListValue(value = "HLTH-EV Public Swimming Pool/Spa Complaint"),
			@ChoiceListValue(value = "HLTH-EV Report of Retail Sale of Illegal Synthetic Drugs"),
			@ChoiceListValue(value = "HLTH-EV Stagnant Water"), @ChoiceListValue(value = "HLTH-EV Tattoo Facility"),
			@ChoiceListValue(value = "HLTH-Food Borne Illness Alleged"),
			@ChoiceListValue(value = "HLTH-Food Facility Complaint"), @ChoiceListValue(value = "HOC test"),
			@ChoiceListValue(value = "HP Sign Removal"), @ChoiceListValue(value = "HP Sign Removal"),
			@ChoiceListValue(value = "HP Sign Repair"), @ChoiceListValue(value = "HP Sign Request"),
			@ChoiceListValue(value = "HQLZA"), @ChoiceListValue(value = "HVAPU"), @ChoiceListValue(value = "HWEUI"),
			@ChoiceListValue(value = "HWIJC"), @ChoiceListValue(value = "HZGPC"), @ChoiceListValue(value = "ICCPG"),
			@ChoiceListValue(value = "IDYIZ"), @ChoiceListValue(value = "IENER"), @ChoiceListValue(value = "IFOPG"),
			@ChoiceListValue(value = "IGFRU"), @ChoiceListValue(value = "IIZRW"),
			@ChoiceListValue(value = "Illegal Dumping"), @ChoiceListValue(value = "Illegal Dumping new"),
			@ChoiceListValue(value = "Illegal Posting of Signs"), @ChoiceListValue(value = "Illegal Vending"),
			@ChoiceListValue(value = "Improper Storage of Trash (Barrels)"), @ChoiceListValue(value = "Incap Generic"),
			@ChoiceListValue(value = "Incap inquiry"), @ChoiceListValue(value = "INMMQ"),
			@ChoiceListValue(value = "INPYV"), @ChoiceListValue(value = "Inquiry"),
			@ChoiceListValue(value = "Install New Lighting"), @ChoiceListValue(value = "IYATY"),
			@ChoiceListValue(value = "IYBAV"), @ChoiceListValue(value = "JBNGT"), @ChoiceListValue(value = "JDDBV"),
			@ChoiceListValue(value = "JQEWI"), @ChoiceListValue(value = "JRJTZ"), @ChoiceListValue(value = "JWOXV"),
			@ChoiceListValue(value = "JXFEF"), @ChoiceListValue(value = "JZAEY"), @ChoiceListValue(value = "KARJS"),
			@ChoiceListValue(value = "KAUBR"), @ChoiceListValue(value = "KDHLO"), @ChoiceListValue(value = "KFVVI"),
			@ChoiceListValue(value = "KHCRP"), @ChoiceListValue(value = "KKBAS"), @ChoiceListValue(value = "KMVAH"),
			@ChoiceListValue(value = "KOCWX"), @ChoiceListValue(value = "KULQE"), @ChoiceListValue(value = "KXTGC"),
			@ChoiceListValue(value = "KZXAS"), @ChoiceListValue(value = "LCCKD"),
			@ChoiceListValue(value = "Lead Paint"), @ChoiceListValue(value = "Litter Basket Maintenance"),
			@ChoiceListValue(value = "LIVKY"), @ChoiceListValue(value = "LKCNT"), @ChoiceListValue(value = "LQDKY"),
			@ChoiceListValue(value = "LSJQM"), @ChoiceListValue(value = "LSYKZ"), @ChoiceListValue(value = "LUODZ"),
			@ChoiceListValue(value = "LWAFH"), @ChoiceListValue(value = "LXBGC"), @ChoiceListValue(value = "LZWYX"),
			@ChoiceListValue(value = "LZYCY"), @ChoiceListValue(value = "Major System Failure"),
			@ChoiceListValue(value = "MBTA Request"), @ChoiceListValue(value = "MCQWE"),
			@ChoiceListValue(value = "Mechanical Permit Inspection Request"), @ChoiceListValue(value = "MGIEE"),
			@ChoiceListValue(value = "Misc. Snow Complaint"),
			@ChoiceListValue(value = "Missed Trash/Recycling/Yard Waste/Bulk Item"),
			@ChoiceListValue(value = "Missing/Damaged Sign Repair"), @ChoiceListValue(value = "MMQVX"),
			@ChoiceListValue(value = "MOPNZ"), @ChoiceListValue(value = "MQWUF"), @ChoiceListValue(value = "MRRTL"),
			@ChoiceListValue(value = "MUSRG"), @ChoiceListValue(value = "MVRWV"), @ChoiceListValue(value = "MWAFO"),
			@ChoiceListValue(value = "MXAQB"), @ChoiceListValue(value = "MXOZJ"), @ChoiceListValue(value = "MYGAK"),
			@ChoiceListValue(value = "MyServicename24"), @ChoiceListValue(value = "NAZFS"),
			@ChoiceListValue(value = "NCBOT"), @ChoiceListValue(value = "NDDExotic Pet"),
			@ChoiceListValue(value = "NDYUZ"), @ChoiceListValue(value = "Needle Removal Request"),
			@ChoiceListValue(value = "New Tree Requests"), @ChoiceListValue(value = "News Boxes"),
			@ChoiceListValue(value = "News Boxes"), @ChoiceListValue(value = "NMFGB"),
			@ChoiceListValue(value = "NMRXD"), @ChoiceListValue(value = "NMSSX"), @ChoiceListValue(value = "NMYMJ"),
			@ChoiceListValue(value = "No Utilities - Electricity"), @ChoiceListValue(value = "No Utilities - Flood"),
			@ChoiceListValue(value = "No Utilities - No Water"), @ChoiceListValue(value = "No Utilities - Sewer"),
			@ChoiceListValue(value = "No-Tow Complaint Confirmation"), @ChoiceListValue(value = "NSQCA"),
			@ChoiceListValue(value = "NUNCD"), @ChoiceListValue(value = "NXRDD"), @ChoiceListValue(value = "OCBKE"),
			@ChoiceListValue(value = "OCGFF"), @ChoiceListValue(value = "OFHTB"), @ChoiceListValue(value = "OFKIQ"),
			@ChoiceListValue(value = "OHGVZ"), @ChoiceListValue(value = "Oil Truck - Weights & Measures"),
			@ChoiceListValue(value = "OJMKM"), @ChoiceListValue(value = "ONHCV"), @ChoiceListValue(value = "OOXZB"),
			@ChoiceListValue(value = "ORYAT"), @ChoiceListValue(value = "OSYCK"),
			@ChoiceListValue(value = "Other - Weights & Measures"), @ChoiceListValue(value = "OTPEX"),
			@ChoiceListValue(value = "OTWVR"), @ChoiceListValue(value = "Overcrowding"),
			@ChoiceListValue(value = "Overgrown Vegetation"), @ChoiceListValue(value = "Park Carpentry"),
			@ChoiceListValue(value = "Park Graffiti"), @ChoiceListValue(value = "Park Horticulture Service"),
			@ChoiceListValue(value = "Park Improvement Requests"), @ChoiceListValue(value = "Park Painting"),
			@ChoiceListValue(value = "Park Painting Test"), @ChoiceListValue(value = "Park Plumbing"),
			@ChoiceListValue(value = "Park Welding"), @ChoiceListValue(value = "Parking Enforcement"),
			@ChoiceListValue(value = "Parking Meter Repairs"),
			@ChoiceListValue(value = "Parking on Front/Back Yards (Illegal Parking)"),
			@ChoiceListValue(value = "Parks General Request"),
			@ChoiceListValue(value = "Parks Lighting/Electrical Issues"),
			@ChoiceListValue(value = "Pavement Marking Inspection"),
			@ChoiceListValue(value = "Pavement Marking Maintenance"), @ChoiceListValue(value = "PEBYG"),
			@ChoiceListValue(value = "PEXID"), @ChoiceListValue(value = "PGRAS"), @ChoiceListValue(value = "PHLYH"),
			@ChoiceListValue(value = "PHSAW"), @ChoiceListValue(value = "PHUFD"), @ChoiceListValue(value = "PIBAF"),
			@ChoiceListValue(value = "Pick up Dead Animal"), @ChoiceListValue(value = "Pickup Clear Conduit"),
			@ChoiceListValue(value = "PJQOA"), @ChoiceListValue(value = "PJZBH"), @ChoiceListValue(value = "PNBKY"),
			@ChoiceListValue(value = "PONXN"), @ChoiceListValue(value = "Poor Ventilation"),
			@ChoiceListValue(value = "PPUKX"), @ChoiceListValue(value = "Price Issues - Weights & Measures"),
			@ChoiceListValue(value = "PRO-SR-AZNJ9297"), @ChoiceListValue(value = "PRO-SR-BPFE9680"),
			@ChoiceListValue(value = "PRO-SR-BSHB8044"), @ChoiceListValue(value = "PRO-SR-BYGJ1375"),
			@ChoiceListValue(value = "PRO-SR-BYIV9237"), @ChoiceListValue(value = "PRO-SR-CXLI6978"),
			@ChoiceListValue(value = "PRO-SR-DFGW6615"), @ChoiceListValue(value = "PRO-SR-EHGT6368"),
			@ChoiceListValue(value = "PRO-SR-GGPR0279"), @ChoiceListValue(value = "PRO-SR-GMFA4611"),
			@ChoiceListValue(value = "PRO-SR-GUKN3634"), @ChoiceListValue(value = "PRO-SR-HDSU2960"),
			@ChoiceListValue(value = "PRO-SR-HYVO3098"), @ChoiceListValue(value = "PRO-SR-ISGS6063"),
			@ChoiceListValue(value = "PRO-SR-JJBA8223"), @ChoiceListValue(value = "PRO-SR-KOKE4538"),
			@ChoiceListValue(value = "PRO-SR-LZNA3696"), @ChoiceListValue(value = "PRO-SR-NBFA6932"),
			@ChoiceListValue(value = "PRO-SR-NIXO1819"), @ChoiceListValue(value = "PRO-SR-NLEW4169"),
			@ChoiceListValue(value = "PRO-SR-NQIZ0791"), @ChoiceListValue(value = "PRO-SR-NXIU2374"),
			@ChoiceListValue(value = "PRO-SR-OIQN0947"), @ChoiceListValue(value = "PRO-SR-PXUZ3685"),
			@ChoiceListValue(value = "PRO-SR-QDUL1123"), @ChoiceListValue(value = "PRO-SR-QTPE5704"),
			@ChoiceListValue(value = "PRO-SR-RLEJ4439"), @ChoiceListValue(value = "PRO-SR-RRGN8096"),
			@ChoiceListValue(value = "PRO-SR-SCHV1837"), @ChoiceListValue(value = "PRO-SR-SIQZ2900"),
			@ChoiceListValue(value = "PRO-SR-SKIC0400"), @ChoiceListValue(value = "PRO-SR-TCSA1788"),
			@ChoiceListValue(value = "PRO-SR-TMCD8351"), @ChoiceListValue(value = "PRO-SR-TYCO2297"),
			@ChoiceListValue(value = "PRO-SR-UEFD8639"), @ChoiceListValue(value = "PRO-SR-VHCR3868"),
			@ChoiceListValue(value = "PRO-SR-VHYU4449"), @ChoiceListValue(value = "PRO-SR-VOSU5288"),
			@ChoiceListValue(value = "PRO-SR-WDDJ0837"), @ChoiceListValue(value = "PRO-SR-WQDX6644"),
			@ChoiceListValue(value = "PRO-SR-WYRH4012"), @ChoiceListValue(value = "PRO-SR-XLHD6143"),
			@ChoiceListValue(value = "PRO-SR-XZKD9296"), @ChoiceListValue(value = "PRO-SR-YEOD0918"),
			@ChoiceListValue(value = "PRO-SR-YHFI1770"), @ChoiceListValue(value = "PRO-SR-YTCQ2966"),
			@ChoiceListValue(value = "Protection of Adjoining Property"),
			@ChoiceListValue(value = "Provar - Schedule - SR"), @ChoiceListValue(value = "Provar Reg Date Check"),
			@ChoiceListValue(value = "Provar Regression RWH"), @ChoiceListValue(value = "Provar Regression Test SR"),
			@ChoiceListValue(value = "Provar Regression with RH"), @ChoiceListValue(value = "Provar Regression WRH"),
			@ChoiceListValue(value = "Provar Regression WRWH"), @ChoiceListValue(value = "Provar System Gen"),
			@ChoiceListValue(value = "Provar-Bus-Hours"), @ChoiceListValue(value = "Provar-POC-1"),
			@ChoiceListValue(value = "Provar-POC-2"), @ChoiceListValue(value = "Provar-POC-3"),
			@ChoiceListValue(value = "Provar-POC-4"), @ChoiceListValue(value = "Provar-POC-5"),
			@ChoiceListValue(value = "Provar-Service-Question"), @ChoiceListValue(value = "PRQAI"),
			@ChoiceListValue(value = "PRYMB"), @ChoiceListValue(value = "PTUCC"),
			@ChoiceListValue(value = "Public Works General Request"), @ChoiceListValue(value = "QBCYG"),
			@ChoiceListValue(value = "QBMJN"), @ChoiceListValue(value = "QECTN"), @ChoiceListValue(value = "QEWKH"),
			@ChoiceListValue(value = "QHAHM"), @ChoiceListValue(value = "QPSSK"), @ChoiceListValue(value = "QVUTV"),
			@ChoiceListValue(value = "QWJNV"), @ChoiceListValue(value = "QXFER"), @ChoiceListValue(value = "Rat Bite"),
			@ChoiceListValue(value = "RBCWL"), @ChoiceListValue(value = "RDYKH"),
			@ChoiceListValue(value = "Recycling Cart Inquiry"), @ChoiceListValue(value = "Recycling Cart Inquiry new"),
			@ChoiceListValue(value = "Recycling Cart Return"),
			@ChoiceListValue(value = "Rental Unit Delivery Conditions"),
			@ChoiceListValue(value = "Request for Litter Basket Installation"),
			@ChoiceListValue(value = "Request for Pothole Repair"),
			@ChoiceListValue(value = "Request for Recycling Cart"),
			@ChoiceListValue(value = "Request for Snow Plowing"),
			@ChoiceListValue(value = "Request for Snow Plowing (Emergency Responder)"),
			@ChoiceListValue(value = "Requests for Street Cleaning"),
			@ChoiceListValue(value = "Reweigh/Short Measure - Weights & Measures"), @ChoiceListValue(value = "RFEYZ"),
			@ChoiceListValue(value = "RKHMZ"), @ChoiceListValue(value = "RLUZU"), @ChoiceListValue(value = "RNOMD"),
			@ChoiceListValue(value = "RNRJT"), @ChoiceListValue(value = "Roadway Repair"),
			@ChoiceListValue(value = "Rodent Activity"), @ChoiceListValue(value = "Rooftop & Mechanical Disturbances"),
			@ChoiceListValue(value = "RSKYZ"), @ChoiceListValue(value = "RWLJD"), @ChoiceListValue(value = "RZHDV"),
			@ChoiceListValue(value = "SajivTest-Aug-01"), @ChoiceListValue(value = "Scale - Weights & Measures"),
			@ChoiceListValue(value = "Schedulable SR-Harsha"), @ChoiceListValue(value = "Schedulable-Item SR"),
			@ChoiceListValue(value = "Schedule a Bulk Item Pickup"), @ChoiceListValue(value = "School Administration"),
			@ChoiceListValue(value = "SEANTESTA"), @ChoiceListValue(value = "SEANTESTB"),
			@ChoiceListValue(value = "Service_Name"), @ChoiceListValue(value = "SHDKZ"),
			@ChoiceListValue(value = "Sideguard - Weights & Measures"),
			@ChoiceListValue(value = "Sidewalk Cover / Manhole"), @ChoiceListValue(value = "Sidewalk Repair"),
			@ChoiceListValue(value = "Snow Buildup Removal (Emergency Agency)"),
			@ChoiceListValue(value = "Snow Removal"), @ChoiceListValue(value = "Space Savers"),
			@ChoiceListValue(value = "Squalid Living Conditions/Hoarding"), @ChoiceListValue(value = "SSFJE"),
			@ChoiceListValue(value = "Stagnant Water"), @ChoiceListValue(value = "STESTA02"),
			@ChoiceListValue(value = "Sticker Request"), @ChoiceListValue(value = "Street Light Knock Downs"),
			@ChoiceListValue(value = "Street Light Outage test"), @ChoiceListValue(value = "Street Light Outages"),
			@ChoiceListValue(value = "Street Light Poles Highway"), @ChoiceListValue(value = "SXCOW"),
			@ChoiceListValue(value = "SZEKJ"), @ChoiceListValue(value = "SZTBR"),
			@ChoiceListValue(value = "Taxi - Transportation Complaint - AVI"),
			@ChoiceListValue(value = "Taxi Meter - Weights & Measures"), @ChoiceListValue(value = "Test"),
			@ChoiceListValue(value = "test"), @ChoiceListValue(value = "test"), @ChoiceListValue(value = "test"),
			@ChoiceListValue(value = "test 1234567"), @ChoiceListValue(value = "test 343"),
			@ChoiceListValue(value = "test 42"), @ChoiceListValue(value = "test 456"),
			@ChoiceListValue(value = "test 55"), @ChoiceListValue(value = "Test 564"),
			@ChoiceListValue(value = "test 765"), @ChoiceListValue(value = "test 7655"),
			@ChoiceListValue(value = "test 9876"), @ChoiceListValue(value = "Test for Transfers"),
			@ChoiceListValue(value = "Test Oct 2017"), @ChoiceListValue(value = "test recycling cart inquiry"),
			@ChoiceListValue(value = "Test Upgrade Existing Lighting"), @ChoiceListValue(value = "Test Version1"),
			@ChoiceListValue(value = "Test-03-20_1"), @ChoiceListValue(value = "Test-03-20_2"),
			@ChoiceListValue(value = "Test-May-07-01"), @ChoiceListValue(value = "TEST-PROVAR-JUL-POC-1"),
			@ChoiceListValue(value = "TEST-PROVAR-JUL-POC-1"), @ChoiceListValue(value = "TEST-PROVAR-JUL-POC-1"),
			@ChoiceListValue(value = "TEST-PROVAR-JUL-POC-1"), @ChoiceListValue(value = "TEST-PROVAR-JUL-POC-1"),
			@ChoiceListValue(value = "TEST-PROVAR-JUL-POC-1"), @ChoiceListValue(value = "Test-S-M-2017-03-01-01"),
			@ChoiceListValue(value = "Test-Service-Name-Jul-01"), @ChoiceListValue(value = "Test-Service-Type-J-28-01"),
			@ChoiceListValue(value = "TEST-ST-10-JUL-01"), @ChoiceListValue(value = "TEST-ST-10-JUL-02"),
			@ChoiceListValue(value = "test09"), @ChoiceListValue(value = "test1223"),
			@ChoiceListValue(value = "test129"), @ChoiceListValue(value = "test2"), @ChoiceListValue(value = "test234"),
			@ChoiceListValue(value = "test3"), @ChoiceListValue(value = "test433"), @ChoiceListValue(value = "test444"),
			@ChoiceListValue(value = "test521"), @ChoiceListValue(value = "test521"), @ChoiceListValue(value = "test6"),
			@ChoiceListValue(value = "test774"), @ChoiceListValue(value = "test89"),
			@ChoiceListValue(value = "test9182"), @ChoiceListValue(value = "TestServiceName"),
			@ChoiceListValue(value = "testTest _78"), @ChoiceListValue(value = "TestTree Emergency"),
			@ChoiceListValue(value = "test_0"), @ChoiceListValue(value = "test_1234"),
			@ChoiceListValue(value = "test_19"), @ChoiceListValue(value = "Test_21_3"),
			@ChoiceListValue(value = "test_432"), @ChoiceListValue(value = "test_654"),
			@ChoiceListValue(value = "test_654"), @ChoiceListValue(value = "test_87"),
			@ChoiceListValue(value = "test_98"), @ChoiceListValue(value = "test_98"),
			@ChoiceListValue(value = "test_demo"), @ChoiceListValue(value = "test_demo1"),
			@ChoiceListValue(value = "test_demo1 service name"), @ChoiceListValue(value = "THJBM"),
			@ChoiceListValue(value = "Traffic Signal Inspection"), @ChoiceListValue(value = "Traffic Signal Repair"),
			@ChoiceListValue(value = "Transportation General Request"), @ChoiceListValue(value = "Tree Emergencies"),
			@ChoiceListValue(value = "Tree Emergency"), @ChoiceListValue(value = "Tree Emergency new"),
			@ChoiceListValue(value = "Tree in Park"), @ChoiceListValue(value = "Tree Maintenance Requests"),
			@ChoiceListValue(value = "TSTVB"), @ChoiceListValue(value = "ULYFG"),
			@ChoiceListValue(value = "Unsafe Dangerous Conditions"),
			@ChoiceListValue(value = "Unsanitary Conditions - Camps"),
			@ChoiceListValue(value = "Unsanitary Conditions - Employees"),
			@ChoiceListValue(value = "Unsanitary Conditions - Establishment"),
			@ChoiceListValue(value = "Unsanitary Conditions - Food"),
			@ChoiceListValue(value = "Unsanitary Conditions - Pools"),
			@ChoiceListValue(value = "Unsanitary Trash Conditions"),
			@ChoiceListValue(value = "Unsatisfactory Living Conditions"),
			@ChoiceListValue(value = "Unshoveled Sidewalk"), @ChoiceListValue(value = "Upgrade Existing Lighting"),
			@ChoiceListValue(value = "Upgrade Existing Lighting"), @ChoiceListValue(value = "UQJQS"),
			@ChoiceListValue(value = "URUPP"), @ChoiceListValue(value = "Utility Casting Repair"),
			@ChoiceListValue(value = "UTJGI"), @ChoiceListValue(value = "UTLAA"), @ChoiceListValue(value = "UTPLW"),
			@ChoiceListValue(value = "UUHWC"), @ChoiceListValue(value = "UXKHA"),
			@ChoiceListValue(value = "Vacant Lot - Land Not Maintained"), @ChoiceListValue(value = "VHQRX"),
			@ChoiceListValue(value = "VJHHN"), @ChoiceListValue(value = "VNICA"), @ChoiceListValue(value = "VPEQY"),
			@ChoiceListValue(value = "VUXSB"), @ChoiceListValue(value = "WAOQB"), @ChoiceListValue(value = "WBAOT"),
			@ChoiceListValue(value = "WFOAI"), @ChoiceListValue(value = "WFYGO"), @ChoiceListValue(value = "WIUZO"),
			@ChoiceListValue(value = "WJJJT"), @ChoiceListValue(value = "WMGVC"), @ChoiceListValue(value = "WNZCP"),
			@ChoiceListValue(value = "WOODY"), @ChoiceListValue(value = "Work Hours-Loud Noise Complaints"),
			@ChoiceListValue(value = "WPFWS"), @ChoiceListValue(value = "WRPID"), @ChoiceListValue(value = "WUSMN"),
			@ChoiceListValue(value = "WVDQB"), @ChoiceListValue(value = "WW-Sewer Water In Basement"),
			@ChoiceListValue(value = "WW-Water Leak (Exterior)"), @ChoiceListValue(value = "WXUSG"),
			@ChoiceListValue(value = "XCAMR"), @ChoiceListValue(value = "XCZSN"), @ChoiceListValue(value = "XDNGA"),
			@ChoiceListValue(value = "XDVOC"), @ChoiceListValue(value = "XDWEG"), @ChoiceListValue(value = "XEKXW"),
			@ChoiceListValue(value = "XKZCS"), @ChoiceListValue(value = "XYGQF"), @ChoiceListValue(value = "YCDDY"),
			@ChoiceListValue(value = "YGSSK"), @ChoiceListValue(value = "YHDSO"), @ChoiceListValue(value = "YHQZK"),
			@ChoiceListValue(value = "YLJTO"), @ChoiceListValue(value = "YNQGZ"), @ChoiceListValue(value = "YNVGM"),
			@ChoiceListValue(value = "YOYFI"), @ChoiceListValue(value = "YPLTZ"), @ChoiceListValue(value = "YUJLP"),
			@ChoiceListValue(value = "YUQES"), @ChoiceListValue(value = "YWXNT"), @ChoiceListValue(value = "YYUDR"),
			@ChoiceListValue(value = "YZXVD"), @ChoiceListValue(value = "ZFTSG"), @ChoiceListValue(value = "ZGKLE"),
			@ChoiceListValue(value = "ZQGYM"), @ChoiceListValue(value = "ZRKKR"), @ChoiceListValue(value = "ZUGAZ"),
			@ChoiceListValue(value = "ZUJVE"), @ChoiceListValue(value = "ZWMAW"), @ChoiceListValue(value = "ZZKYD"),
			@ChoiceListValue(value = "ZZMUZ") })
	@FindBy(xpath = "//tr/td[1]/select/option[contains(text(),'Provar Regression RWH')]")
	public WebElement availableTypesSelectProvarRegressionRWH;
	@ButtonType()
	@VisualforceBy(componentXPath = "apex:commandButton[@action='{! save }']")
	public WebElement save;
	@LinkType()
	@FindBy(xpath = "//td[contains(@class, \"moveButtonCell\")]/div[1]/a")
	public WebElement btnRight;
	
}
